# Generated by Django 3.2 on 2021-04-23 07:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_pics/')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('author', models.CharField(default='Menim', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('body', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('blog_type', models.IntegerField(choices=[(0, 'None'), (1, 'Featured'), (2, 'Trending')], default=0)),
                ('quote', models.CharField(max_length=400, null=True)),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.Category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
