# Generated by Django 3.2 on 2021-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_commentmodel_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
