# Generated by Django 3.2 on 2021-04-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentmodel_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='comment_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='your_name',
            new_name='name',
        ),
    ]
