# Generated by Django 3.2 on 2021-04-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210424_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
    ]
