# Generated by Django 3.2 on 2021-04-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_commentmodel_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='your_name',
        ),
    ]
