# Generated by Django 3.2 on 2021-04-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210424_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
