# Generated by Django 3.2 on 2021-05-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='img_credits',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='img_credits',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='img_credits',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
