# Generated by Django 3.2 on 2021-05-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210514_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='lat_real',
            name='alb_art',
            field=models.ImageField(blank=True, null=True, upload_to='Album_Art/'),
        ),
        migrations.AddField(
            model_name='lat_real',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lat_real',
            name='youtube',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
