# Generated by Django 3.2 on 2021-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210516_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lat_real',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lat_real',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
