# Generated by Django 3.2 on 2021-07-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_lat_real_music_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lat_Real',
        ),
    ]
