# Generated by Django 3.2 on 2021-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_delete_lat_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='blog_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Featured'), (2, 'Trending')], default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='blog_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Featured'), (2, 'Trending')], default=0),
        ),
    ]
