# Generated by Django 3.2 on 2021-10-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210712_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lists',
        ),
    ]
